config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  require 'sidekiq/web'
  Sidekiq::Web.set :sessions, false

  require 'sidekiq-status/web'
  mount Sidekiq::Web => '/sidekiq'

  root to: 'home#index'

  namespace :admin do
    resources :salons
  end

  namespace :api, defaults: { format: :json } do
    post 'auth', to: 'authentication#authenticate_user'
    get 'me', to: 'users#me'

    resources :salons do
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/salon.rb
# == Schema Information
#
# Table name: salons
#
#  id           :bigint(8)        not null, primary key
#  name         :string(255)
#  desc         :text(65535)
#  address      :text(65535)
#  phone_number :string(255)
#  created_at   :datetime
#  updated_at   :datetime
#

class Salon < ApplicationRecord
  acts_as_paranoid

  validates :name, presence: true
end

app/models/salon_request_service.rb
# == Schema Information
#
# Table name: salon_request_services
#
#  id                        :bigint(8)        not null, primary key
#  salon_schedule_request_id :bigint(8)
#  salon_service_id          :bigint(8)
#  created_at                :datetime
#  updated_at                :datetime
#

class SalonRequestService < ApplicationRecord

end

app/models/salon_schedule.rb
# == Schema Information
#
# Table name: salon_schedules
#
#  id         :bigint(8)        not null, primary key
#  salon_id   :bigint(8)
#  user_id    :bigint(8)
#  start_time :datetime
#  end_time   :datetime
#  created_at :datetime
#  updated_at :datetime
#

class SalonSchedule < ApplicationRecord

end

app/models/salon_schedule_request.rb
# == Schema Information
#
# Table name: salon_schedule_requests
#
#  id         :bigint(8)        not null, primary key
#  user_id    :bigint(8)
#  salon_id   :bigint(8)
#  start_time :datetime
#  created_at :datetime
#  updated_at :datetime
#

class SalonScheduleRequest < ApplicationRecord

end

app/models/salon_schedule_service.rb
# == Schema Information
#
# Table name: salon_schedule_services
#
#  id                :bigint(8)        not null, primary key
#  salon_service_id  :bigint(8)
#  salon_schedule_id :bigint(8)
#  created_at        :datetime
#  updated_at        :datetime
#

class SalonScheduleService < ApplicationRecord

end

app/models/salon_service.rb
# == Schema Information
#
# Table name: salon_services
#
#  id         :bigint(8)        not null, primary key
#  name       :string(255)
#  desc       :text(65535)
#  start_time :datetime
#  end_time   :datetime
#  created_at :datetime
#  updated_at :datetime
#

class SalonService < ApplicationRecord

end

app/models/salon_user.rb
# == Schema Information
#
# Table name: salon_users
#
#  id         :bigint(8)        not null, primary key
#  salon_id   :bigint(8)
#  user_id    :bigint(8)
#  created_at :datetime
#  updated_at :datetime
#

class SalonUser < ApplicationRecord

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :bigint(8)        not null, primary key
#  email                  :string(255)      default(""), not null
#  encrypted_password     :string(255)      default(""), not null
#  role                   :integer          default("admin"), not null
#  name                   :string(255)
#  phone_number           :string(255)
#  reset_password_token   :string(255)
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  created_at             :datetime
#  updated_at             :datetime
#

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
   devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  enum role: {
    admin: 1,
    salon: 2
  }
end

app/controllers/admin/base_controller.rb
class Admin::BaseController < ApplicationController
  include Pundit
  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  after_action :verify_authorized

  private

  def user_not_authorized
    flash[:alert] = "you are not authorized to perform this action"
    redirect_to(request.referrer || root_path)
  end
end

app/controllers/admin/salons_controller.rb
class Admin::SalonsController < Admin::BaseController
  before_action :set_salon, only: [:show, :edit, :update, :destroy]
  before_action :authorize_resource, only: [:index, :new, :create]
  before_action :set_page_title

  def index
    @q = Salon.ransack(params[:q])
    @salons = @q.result(distinct: true)
  end

  def new
    @salon = Salon.new
  end

  def create
    @salon = Salon.new(salon_params)
    if @salon.save
      redirect_to edit_admin_salon_path(@salon), notice: 'Successfully created new salon'
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @salon.update(salon_params)
      redirect_to edit_admin_salon_path(@salon), notice: 'Update Salon success'
    else
      render :edit
    end
  end

  def destroy
    if @salon.destroy
      redirect_to admin_salons_path, notice: 'Deleted salon'
    else
      redirect_to admin_salons_path, alert: 'Failed to delete salon'
    end
  end

  private

  def set_salon
    @salon = Salon.find(params[:id])

    authorize @salon
  end

  def authorize_resource
    authorize Salon
  end

  def set_page_title
    @title = 'Manage Salons'
  end

  def salon_params
    params.require(:salon).permit(:name, :desc, :phone_number, :address)
  end
end

app/controllers/api/authentication_controller.rb
class Api::AuthenticationController < Api::BaseController
  skip_before_action :authenticate_request!
  protect_from_forgery except: :authenticate_user

  def authenticate_user
    user = User.find_for_database_authentication(email: params[:email])
    if user.valid_password?(params[:password])
      render json: payload(user)
    else
      render json: {
        errors: [
          'Invalid Username/password'
        ]
      }
    end
  end

  def payload(user)
    return nil unless user and user.id
    {
      auth_token: JsonWebToken.encode(
        {
          user_id: user.id,
          exp: (Time.now + 2.week).to_i
        }
      )
    }
  end
end

app/controllers/api/base_controller.rb
class Api::BaseController < ActionController::Base
  include ActionController::MimeResponds
  respond_to :json

  before_action :authenticate_request!

  protected

  def authenticate_request!
    unless user_id_in_token?
      render json: {
        errors: ['Not Authenticated']
      }, status: :unauthorized
      return
    end
    @current_user = User.find(auth_token[:user_id])
  rescue JWT::VerificationError, JWT::DecodeError
    render json: {
      errors: ['Not Authenticated'],
    }, status: :unauthorized
  end

  private

  def http_token
    @http_token ||= if request.headers['Authorization'].present?
                      request.headers['Authorization'].split(' ').last
                    end
  end

  def auth_token
    @auth_token ||= JsonWebToken.decode(http_token)
  end

  def user_id_in_token?
    http_token && auth_token && auth_token[:user_id].to_i
  end
end

app/controllers/api/salons_controller.rb
class Api::SalonsController < Api::BaseController
  def index
    render json: Salon.all
  end
end

app/controllers/api/users_controller.rb
class Api::UsersController < Api::BaseController
  def me
    render json: {
      user: @current_user
    }
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/salons/_form.html.slim
.md-layout-item.md-small-size-100.md-size-100
  - if @salon.errors.any?
    - @salon.errors.full_messages.each do |message|
      .alert.alert-danger
        button.close aria-hidden="true" type="button"
          | ×
        span
          b= message
.md-layout-item.md-small-size-100.md-size-50
  md-field
    = f.label :name
    md-input(name="salon[name]" value="#{@salon.name}")
    span.md-helper-text Helper text
.md-layout-item.md-small-size-100.md-size-50
  md-field
    = f.label :phone_number
    md-input(name="salon[phone_number]" value="#{@salon.phone_number}")
    span.md-helper-text Helper text
.md-layout-item.md-small-size-100.md-size-100
  md-field
    = f.label :address
    md-input(name="salon[address]" value="#{@salon.address}")
    span.md-helper-text Helper text
.md-layout-item.md-size-100
  md-field
    = f.label :desc
    md-input(name="salon[desc]" value="#{@salon.desc}")
    span.md-helper-text Helper text
.md-layout-item.md-size-100.text-right
  = button_tag type: 'submit', class: 'md-button md-raised md-success md-theme-default' do
    .md-ripple
      .md-button-content Submit

app/views/admin/salons/_result.html.slim
.md-layout-item.md-medium-size-100.md-xsmall-size-100.md-size-100
  .md-card.md-theme-default
    .md-card-header data-background-color="green"
      h4.title Salons list
      / p.category Here is a subtitle for this table
    .md-card-content
      .md-content.md-table.md-theme-default table-header-color="green"
        .md-content.md-table-content.md-scrollbar.md-theme-default
          table
            thead
              tr
                th.md-table-head
                  .md-table-head-container.md-ripple.md-disabled
                    .md-table-head-label
                      | Name
                th.md-table-head
                  .md-table-head-container.md-ripple.md-disabled
                    .md-table-head-label
                      | Address
                th.md-table-head
                  .md-table-head-container.md-ripple.md-disabled
                    .md-table-head-label
                      | Phone Number
                th.md-table-head
                  .md-table-head-container.md-ripple.md-disabled
                    .md-table-head-label
                      | Description
            tbody
              - @salons.each do |salon|
                tr.md-table-row
                  td.md-table-cell
                    .md-table-cell-container= salon.name
                  td.md-table-cell
                    .md-table-cell-container= salon.address
                  td.md-table-cell
                    .md-table-cell-container= salon.phone_number
                  td.md-table-cell
                    .md-table-cell-container= salon.desc
                  td.md-table-cell
                    .md-table-cell-container
                      md-menu(md-direction="bottom-start")
                        md-button(md-menu-trigger) Action
                        md-menu-content
                          md-menu-item
                            = link_to 'Edit', edit_admin_salon_path(salon)
                          md-menu-item
                            = link_to 'Delete', admin_salon_path(salon), method: :delete, data: { confirm: 'Are you sure?' }

app/views/admin/salons/_search.html.slim
.md-layout-item.md-medium-size-100.md-xsmall-size-100.md-size-100
  .md-card.md-theme-default
    .md-card-header data-background-color="green"
      h4.title Salons Search
    .md-card-content
      .md-layout.md-gutter
        = search_form_for [:admin, @q], class: 'md-layout' do |f|
          .md-layout-item.md-size-50
            md-field
              = f.label :name
              md-input(name="q[name_cont]" value="#{params.dig(:q, :name_cont)}")

          .md-layout-item.md-size-50
            md-field
              = f.label :desc
              md-input(name="q[desc_cont]" value="#{params.dig(:q, :desc_cont)}")

          .md-layout-item.md-size-50
            md-field
              = f.label :address
              md-input(name="q[address_cont]" value="#{params.dig(:q, :address_cont)}")

          .md-layout-item.md-size-50
            md-field
              = f.label :phone_number
              md-input(name="q[phone_number_cont]" value="#{params.dig(:q, :phone_number_cont)}")

          .md-layout-item.md-small-size-100
            md-button.md-primary(type='submit' value="Search") Search

app/views/admin/salons/edit.html.slim
.md-layout
  .md-layout-item.md-medium-size-100
    = form_for [:admin, @salon] do |f|
      .md-card.md-theme-default
        .md-card-header data-background-color="green"
          h4.title Edit salon
          p.category= @salon.name
        .md-card-content
          .md-layout
           = render 'form', f: f

app/views/admin/salons/index.html.slim
.md-layout
  = render "search"
  = render "result"

app/views/admin/salons/new.html.slim
.md-layout
  .md-layout-item.md-medium-size-100
    = form_for [:admin, @salon] do |f|
      .md-card.md-theme-default
        .md-card-header data-background-color="green"
          h4.title Create new salon
          / p.category Complete your profile
        .md-card-content
          .md-layout
           = render 'form', f: f

app/views/home/index.html.slim
| Home page for loggedin user

app/views/layouts/application.html.slim
doctype html
html
  head
    title Admin
    = csrf_meta_tags
    = csp_meta_tag

    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application'
    = stylesheet_pack_tag 'application'

    meta content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0" name="viewport" /
    /! Fonts and icons
    link href="//fonts.googleapis.com/css?family=Roboto:300,400,500,700,400italic" rel="stylesheet"
    link href="//fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet"
    link href="https://use.fontawesome.com/releases/v5.0.8/css/all.css" rel="stylesheet"

  body
    - if user_signed_in?
      #app.wrapper
        .notice= notice
        .alert= alert
        = render "layouts/shared/sidebar"
        div(data-color="green")
        = yield
    - else
      = yield

app/views/layouts/devise.html.slim
doctype html
html
  head
    title Admin
    = csrf_meta_tags
    = csp_meta_tag

    = stylesheet_link_tag    'devise', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'devise', 'data-turbolinks-track': 'reload'

    meta content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0" name="viewport" /

  body
    = yield

app/views/layouts/shared/_notification.html.slim
.md-layout-item.md-medium-size-100
  - if notice
    .alert.alert-success= notice
  - if alert
    .alert.alert-warning= alert

app/views/layouts/shared/_sidebar.html.slim
.sidebar#sidebar data-color="green" style="background-image: url(#{asset_path('sidebar-2.jpg')})"
  .logo
    a.simple-text.logo-mini href="#" /
    .logo-img
      = image_tag "vue-logo.png"
    a.simple-text.logo-normal href="https://www.creative-tim.com/product../" target="_blank"
      | Vue MD
  .sidebar-wrapper
    = render "layouts/shared/sidebar_list_#{current_user.role}"

app/views/layouts/shared/_sidebar_list_admin.html.slim
ul.md-list.nav.md-theme-default
  li.md-list-item
    = active_link_to admin_salons_path, class: "md-list-item-router md-list-item-container md-button-clean", class_active: 'nav-item active router-link-active' do
      .md-list-item-content.md-ripple
        i.md-icon.md-icon-font.md-theme-default dashboard
        p Manage Salons
        span
  li.md-list-item
    a.md-list-item-router.md-list-item-container.md-button-clean href="#/user" mdripple="true"
      .md-list-item-content.md-ripple
        i.md-icon.md-icon-font.md-theme-default person
        p User Profile
        span
  li.md-list-item
    a.md-list-item-router.md-list-item-container.md-button-clean href="#/table" mdripple="true"
      .md-list-item-content.md-ripple
        i.md-icon.md-icon-font.md-theme-default content_paste
        p Table list
        span
  li.md-list-item
    a.md-list-item-router.md-list-item-container.md-button-clean href="#/typography" mdripple="true"
      .md-list-item-content.md-ripple
        i.md-icon.md-icon-font.md-theme-default library_books
        p Typography
        span
  li.md-list-item
    a.md-list-item-router.md-list-item-container.md-button-clean href="#/icons" mdripple="true"
      .md-list-item-content.md-ripple
        i.md-icon.md-icon-font.md-theme-default bubble_chart
        p Icons
        span
  li.md-list-item
    a.md-list-item-router.md-list-item-container.md-button-clean href="#/maps" mdripple="true"
      .md-list-item-content.md-ripple
        i.md-icon.md-icon-font.md-theme-default location_on
        p Maps
        span
  li.md-list-item
    a.md-list-item-router.md-list-item-container.md-button-clean href="#/notifications" mdripple="true"
      .md-list-item-content.md-ripple
        i.md-icon.md-icon-font.md-theme-default notifications
        p Notifications
        span
  li.md-list-item.active-pro
    = link_to destroy_user_session_path, method: :delete, class: 'md-list-item-router md-list-item-container md-button-clean' do
      .md-list-item-content.md-ripple
        i.fas.fa-sign-out-alt
        p Sign Out
        span

app/views/layouts/shared/_toolbar.html.slim
.md-toolbar.md-transparent.md-theme-default.md-elevation-0
  .md-toolbar-row
    .md-toolbar-section-start
      h3.md-title = @title || "Dashboard"
    .md-toolbar-section-end
      button.md-button.md-just-icon.md-simple.md-toolbar-toggle.md-theme-default type="button"
        .md-ripple
          .md-button-content
            span.icon-bar
            span.icon-bar
            span.icon-bar
          span
      .md-collapse
        .md-autocomplete
          .md-field.md-autocomplete.search.md-theme-default.md-clearable
            .md-menu
              input#md-input-3oyilfjhm.md-input type="text" /
            label Search...
            /!
            /!
            /!
        ul.md-list.md-theme-default
          li.md-list-item to="/"
            a.md-list-item-router.md-list-item-container.md-button-clean.router-link-active href="#/" mdripple="true"
              .md-list-item-content.md-ripple
                i.material-icons dashboard
                p.hidden-lg.hidden-md Dashboard
                span
          li.md-list-item.dropdown to="/notifications"
            a.md-list-item-router.md-list-item-container.md-button-clean href="#/notifications" mdripple="true"
              .md-list-item-content.md-ripple
                .dropdown
                  a.dropdown-toggle data-toggle="dropdown"
                    i.material-icons notifications
                    span.notification 5
                  p.hidden-lg.hidden-md Notifications
                  ul.dropdown-menu.dropdown-menu-right
                    li
                      a href="#"  Mike John responded to your email
                    li
                      a href="#"  You have 5 new tasks
                    li
                      a href="#"  You're now friend with Andrew
                    li
                      a href="#"  Another Notification
                    li
                      a href="#"  Another One
                span
          li.md-list-item to="/user"
            a.md-list-item-router.md-list-item-container.md-button-clean href="#/user" mdripple="true"
              .md-list-item-content.md-ripple
                i.material-icons person
                p.hidden-lg.hidden-md Profile
                span